### ISSUE TITLE
如何动态设置轮播图片的高度？

### ISSUE THREAD

**Issue by ywanhzy** [bingoogolapple/BGABanner-Android#100]
如何动态设置轮播图片的高度？
  mDefaultBanner.setAdapter(new BGABanner.Adapter<ImageView, String>() {
            @Override
            public void fillBannerItem(BGABanner banner, ImageView itemView, String model, int position) {
               ViewGroup.LayoutParams params = itemView.getLayoutParams();
               params.width =imgwidth;
               params.height=imgwidth;
               itemView.setLayoutParams(params);
                Glide.with(MallDetailActivity.this)
                        .load(model)
                        .placeholder(R.mipmap.holder)
                        .error(R.mipmap.holder)
                        .centerCrop()
                        .dontAnimate()
                        .into(itemView);
            }
        });
在这里加直接报错

**Comment by ywanhzy** [comment]
已经解决了

**Comment by Troll4it** [comment]
@ywanhzy 我最近也在弄这个，请问您怎么做的
