### ISSUE TITLE
app:banner_pointDrawable=""处设置不同的drawable

### ISSUE THREAD

**Issue by taixiang** [bingoogolapple/BGABanner-Android#110]
想要实现的效果是：旋中的指示器是椭圆形的，其余未选中的是圆形的，
app:banner_pointDrawable="@drawable/selector_home_indicator"
对应的selector写好了，但是实际效果都是椭圆的样子
不知道是不是源码中以下的问题：
if (mPointRealContainerLl != null) {
            if (mViews != null && mViews.size() > 0 && newCurrentPoint < mViews.size() && ((mIsNeedShowIndicatorOnOnlyOnePage || (!mIsNeedShowIndicatorOnOnlyOnePage && mViews.size() > 1)))) {
                mPointRealContainerLl.setVisibility(View.VISIBLE);
                for (int i = 0; i < mPointRealContainerLl.getChildCount(); i++) {
                    mPointRealContainerLl.getChildAt(i).setEnabled(i == newCurrentPoint);
                    // 处理指示器选中和未选中状态图片尺寸不相等
                    mPointRealContainerLl.getChildAt(i).requestLayout();
                }
            } else {
                mPointRealContainerLl.setVisibility(View.GONE);
            }
        }
还望给予意见,,3q

**Comment by bingoogolapple** [comment]
看 demo 中的 selector_banner_unequal.xml

**Comment by payne1107** [comment]
和selector_banner_unequal一样 但是只显示默认的指示器
