### ISSUE TITLE
小米note内存溢出OOM【已自己解决】

### ISSUE THREAD

**Issue by Dvtion** [bingoogolapple/BGABanner-Android#111]
在小米note上，放一张大小为20k的图片就崩溃。引发oom，`java.lang.OutOfMemoryError: Failed to allocate a 6482940 byte allocation with 2818408 free bytes and 2MB until OOM` 原因是你的BGABannerUtil下的getItemImageView` imageView.setImageResource(placeholderResId);`出问题了。。
以下是解决方法
----------------------------------------------------------------------------------------------------------------------
   imageView.setImageBitmap(readBitMap(context, placeholderResId));

 public static Bitmap readBitMap(Context context, int resId){  
        BitmapFactory.Options opt = new BitmapFactory.Options();  
        opt.inPreferredConfig = Bitmap.Config.RGB_565;   
        opt.inPurgeable = true;  
        opt.inInputShareable = true;  
           //获取资源图片  
        InputStream is = context.getResources().openRawResource(resId);  
            return BitmapFactory.decodeStream(is,null,opt);  
    }
[http://263229365.iteye.com/blog/1562924](url)
这是解决链接，希望帮到你

**Comment by bingoogolapple** [comment]
Thanks

**Comment by Dvtion** [comment]
You're welcome

**Comment by Dvtion** [comment]
你什么时候，处理下这个问题，我AS上的没办法自己改

**Comment by bingoogolapple** [comment]
争取今晚吧
