### ISSUE TITLE
[ANR Warning]onMeasure time too long

### ISSUE THREAD

**Issue by xiaomeixw** [bingoogolapple/BGABanner-Android#12]
[ANR Warning]onMeasure time too long, this =xxx.xxxx.xxx.banner.BGAViewPager{41edf5b0 VFED.... ......ID 0,0-1280,752}time =95485 ms
RT...并不是经常发生，而是有时偶发...

**Comment by githubityu** [comment]
BGABanner  setViewsAndTips  use time too long
