### ISSUE TITLE
High memory usage.

### ISSUE THREAD

**Issue by manafzar** [bingoogolapple/BGABanner-Android#150]
I'm using this library in my application to show three pictures in apptoolbarlayout one by one. I have found out that my application takes a lot of memory(around 150 MB) even though it's layout and design is easy and made to be performant without much memory usage. after some investigation in memory profiler i found out that most of this memory is taken by BGABanner to show these pictures. The pictures are not that big and only 150KB in size for each picture and i don't think they should take memory more than 1-2MB each but memory usage with BGABanner enabled is around 110MB more! So can you fix this?

**Comment by manafzar** [comment]
Even Though my pictures are not that big and loaded from drawable directly maybe this helps too for big pictures situations. you can estimate element's size on screen and only save image on that size on the memory. But i'm guessing my situation has another reason other than pixel size.
https://developer.android.com/topic/performance/graphics/load-bitmap.html#read-bitmap

**Comment by ipcjs** [comment]
@ghost You should lower the resolution of your local image instead of dynamically compressing the image through code.
