### ISSUE TITLE
引导图是否有去掉指示小圆点的API

### ISSUE THREAD

**Issue by MelvinCen** [bingoogolapple/BGABanner-Android#156]
请问,引导图是否有去掉指示小圆点的API?

**Comment by luyun181** [comment]
同问

**Comment by bingoogolapple** [comment]
app:banner_pointDrawable 的值传 @android:color/transparent

**Comment by bingoogolapple** [comment]
2.2.7 BGABanner.setIndicatorVisibility(false);
