### ISSUE TITLE
轮播时间间隔

### ISSUE THREAD

**Issue by KevinYou128** [bingoogolapple/BGABanner-Android#16]
你好，轮播时间间隔，banner_pageChangeDuration，banner_pointAutoPlayInterval，这两个值我都设置过了，没起作用怎么回事，，，还有就是动画滑动几个循环后，滑动一半释放手势，这个切换效果会变得有点奇怪，，

**Comment by bingoogolapple** [comment]
@KevinYou128 banner_pageChangeDuration是每一次页面切换的持续时间，banner_pointAutoPlayInterval是指隔多长时间轮播一次。

目前滑动过程中点击item还有问题，使用banner_pageChangeDuration的默认值吧
