### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by JarvisBuop** [bingoogolapple/BGABanner-Android#161]
连续快速的一直滑动下一页,会出现ANR;
初步判断可能是:
BGAbanner - PageAdapter中没有重写destroyItem(..)方法导致的;
好像也不是,多次切换动画条目,偶尔出现的

**Comment by lyldding** [comment]
分析了一下可能是切换的position值不对，导致循环耗时出现ANR，详情见https://blog.csdn.net/lylddingHFFW/article/details/89212664
