### ISSUE TITLE
引导页需要全面屏适配

### ISSUE THREAD

**Issue by kilo-swodh** [bingoogolapple/BGABanner-Android#165]
引导页如果在19:9或者19.5:9的机型上,悬浮的问题显示不全

**Comment by bingoogolapple** [comment]
升级到 2.2.7，根据当前是否全面屏，通过下面的任意方法设置指示器距离底部的距离

BGABanner.setIndicatorTopBottomMarginDp
BGABanner.setIndicatorTopBottomMarginPx
BGABanner.setIndicatorTopBottomMarginRes
