### ISSUE TITLE
在华为5.0.2的手机上 ，用两张不一样大小的图片做指示器的时候有问题

### ISSUE THREAD

**Issue by Luopan1** [bingoogolapple/BGABanner-Android#166]
比如说一张长一点的图片和一个圆形的图片来做指示器，然后切换就有问题了，图片大小几乎成一样了，圆形的图片被拉伸成了长条形的，（长条形的是当前选中的样式  圆形是没选中的样式）。

**Comment by androidliuzemin** [comment]
可以看下我提交的Issue里的解决办法。

**Comment by bingoogolapple** [comment]
看 demo 中的 selector_banner_unequal.xml
