### ISSUE TITLE
2张图不轮播吗

### ISSUE THREAD

**Issue by FebTiankong** [bingoogolapple/BGABanner-Android#168]
2张图不轮播吗

**Comment by bingoogolapple** [comment]
![image](https://user-images.githubusercontent.com/8949716/68065659-676a7680-fd67-11e9-923f-d717b2ea8d8f.png)

**Comment by FebTiankong** [comment]
好的 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"王浩"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月2日(星期六) 中午11:53
收件人:&nbsp;"bingoogolapple/BGABanner-Android"<BGABanner-Android@noreply.github.com&gt;;
抄送:&nbsp;"二月"<854301213@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bingoogolapple/BGABanner-Android] 2张图不轮播吗 (#168)
