### ISSUE TITLE
BGAViewPager没有addOnPageChangeListener方法

### ISSUE THREAD

**Issue by ygeng** [bingoogolapple/BGABanner-Android#17]
public void setViewsAndTips(List<? extends View> views, List<String> tips) {
        if (mAutoPlayAble && views.size() < 3) {
            throw new IllegalArgumentException("开启指定轮播时至少有三个页面");
        }
        if (tips != null && tips.size() != views.size()) {
            throw new IllegalArgumentException("提示文案数必须等于页面数量");
        }
        mViews = views;
        mTips = tips;
        mViewPager.setAdapter(new PageAdapter());
        mViewPager.**addOnPageChangeListener**(new ChangePointListener());

        initPoints();
        processAutoPlay();
    }
调用setViews()方法时，会报错提示没有addOnPageChangeListener方法

**Comment by bingoogolapple** [comment]
升级一下你的support-v4包

**Comment by lmqwudi** [comment]
最小版本23？
