### ISSUE TITLE
关于4.4模拟器设置不自动滚动的问题

### ISSUE THREAD

**Issue by wzgl5533** [bingoogolapple/BGABanner-Android#173]
1、代码中设置了不自动滚动 banner.setAutoPlayAble(false);
2、设置setOnPageChangeListener
出现概率事件：banner会出现监听到滚动下一页的情况，其他高版本好像没有这个问题？
请问这是怎么回事

**Comment by bingoogolapple** [comment]
升级到到 2.2.7
