### ISSUE TITLE
使用Glide加载圆角图片没有效果 

### ISSUE THREAD

**Issue by corffen** [bingoogolapple/BGABanner-Android#175]
Glide.with(getContext())
                        .load(url)
                        .apply(RequestOptions.bitmapTransform(new RoundedCorners(20)))
                        .into(imageView);

加载圆角等使用的库是glide-transformations

**Comment by 15321657258** [comment]
我也遇到这个问题，怎么解决的？？万分感谢

**Comment by bingoogolapple** [comment]
内部设置了 itemView 的 scaleType 为 centerCrop

1、Glide transform 是针对内存中的图片进行裁剪
2、裁剪完设置到 itemView 时又经过了 centerCrop 裁剪，由于图片宽高比和 itemView 的宽高比不一样，所以经过 centerCrop 裁剪后 Glide 生成的圆角已经被裁剪掉了

**Comment by alanzyz** [comment]
itemView.setScaleType(ImageView.ScaleType.FIT_XY) 不生效

**Comment by alanzyz** [comment]
部分图片未显示
