### ISSUE TITLE
空数据就隐藏，刷新有新数据时，需要显示出来，但是如何设置都不行。。。。。。。。

### ISSUE THREAD

**Issue by zcweng** [bingoogolapple/BGABanner-Android#179]
空数据就隐藏，刷新有新数据时，需要显示出来，但是如何设置都不行。。。。。。。。空数据就隐藏，刷新有新数据时，需要显示出来，但是如何设置都不行。。。。。。。。空数据就隐藏，刷新有新数据时，需要显示出来，但是如何设置都不行。。。。。。。。空数据就隐藏，刷新有新数据时，需要显示出来，但是如何设置都不行。。。。。。。。空数据就隐藏，刷新有新数据时，需要显示出来，但是如何设置都不行。。。。。。。。

**Comment by bingoogolapple** [comment]
![image](https://user-images.githubusercontent.com/8949716/68067548-81b24d80-fd83-11e9-9a11-666a9ccd62bd.png)
