### ISSUE TITLE
cpu占用率略高，基本轮播后和轮播时的占用率能差出百分之十九

### ISSUE THREAD

**Issue by Guangdinghou** [bingoogolapple/BGABanner-Android#18]
cpu占用率略高，基本轮播后和轮播时的占用率能差出百分之十九

**Comment by bingoogolapple** [comment]
@Guangdinghou 麻烦试一下最新版本v2.0.6还有没有这个问题，谢谢

**Comment by SomnusWu** [comment]
cpu占用率略高  用的  compile 'cn.bingoogolapple:bga-banner:2.0.9@aar'  版本 。有办法处理下么

**Comment by bingoogolapple** [comment]
最新版 v2.2.3
