### ISSUE TITLE
怎样设置类似小红书根据图片高度自适应高度轮播图

### ISSUE THREAD

**Issue by 921668753** [bingoogolapple/BGABanner-Android#181]
怎样设置类似小红书根据图片高度自适应高度轮播图

**Comment by 921668753** [comment]
怎样设置类似小红书根据图片高度自适应高度轮播图

**Comment by po1arbear** [comment]
mBanner = homepageHeader.findViewById(R.id.banner)
        val params = mBanner.layoutParams
        params.height = (SystemUtils.getScreenWidth(activity) * AppConstant.BANNER_PROPORTION).toInt()
        mBanner.layoutParams = params
获取屏幕宽度，根据图片比例设置高度

**Comment by 921668753** [comment]
好的，知道了！

**Comment by bingoogolapple** [comment]
![image](https://user-images.githubusercontent.com/8949716/68065618-ef9c4c00-fd66-11e9-88a7-040165abe0af.png)
