### ISSUE TITLE
传入空集合时不显示占位图

### ISSUE THREAD

**Issue by po1arbear** [bingoogolapple/BGABanner-Android#184]
val advertInfos = msg.obj as List<AdvData.AdvertInfo>
                mBanner.run {
                    setData(advertInfos, mutableListOf())
                    setAdapter(object : BGABanner.Adapter<ImageView, AdvData.AdvertInfo> {
                        override fun fillBannerItem(p0: BGABanner?, p1: ImageView?, p2: AdvData.AdvertInfo?, p3: Int) {
                            Glide.with(activity)
                                    .load(p2?.image_url)
                                    .apply(RequestOptions()
                                            .placeholder(R.drawable.ic_banner_placeholder)
                                            .error(R.drawable.ic_banner_placeholder)
                                            .centerCrop()
                                    )
                                    .into(p1)
                        }
                    })

**Comment by bingoogolapple** [comment]
传入空集合时展示的占位图是通过 banner_placeholderDrawable 配置
