### ISSUE TITLE
快速左右滑动，直接卡死

### ISSUE THREAD

**Issue by Mystrawberry** [bingoogolapple/BGABanner-Android#200]
快速左右滑动，直接卡死

**Comment by hero0812** [comment]
报ANR了，log如下：
ctivityManager: ANR in cn.bingoogolapple.bgabanner.demo (cn.bingoogolapple.bgabanner.demo/.ui.activity.MainActivity)
    PID: 5591
    Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 26.  Wait queue head age: 5563.1ms.)
    Load: 7.41 / 6.72 / 5.87
    CPU usage from 166739ms to 0ms ago (2018-11-21 19:37:53.109 to 2018-11-21 19:40:39.847):
      6.6% 502/surfaceflinger: 3.7% user + 2.8% kernel / faults: 66 minor
      6.1% 885/system_server: 3.7% user + 2.4% kernel / faults: 5393 minor
      4.1% 5418/com.qiyi.video: 1.3% user + 2.7% kernel / faults: 18 minor
      4.1% 1293/com.ustwo.lwp: 1.9% user + 2.1% kernel / faults: 60 minor
      2.8% 7/rcu_preempt: 0% user + 2.8% kernel
      2.3% 4780/com.google.android.googlequicksearchbox:search: 1.7% user + 0.6% kernel / faults: 1344 minor
      2.2% 5230/mdss_fb0: 0% user + 2.2% kernel
      1.9% 4529/com.google.android.gms.persistent: 1.3% user + 0.5% kernel / faults: 4151 minor
      1.7% 504/android.hardware.graphics.composer@2.1-service: 0.8% user + 0.9% kernel / faults: 14 minor
      1.7% 3/ksoftirqd/0: 0% user + 1.7% kernel
      1.5% 662/android.hardware.audio@2.0-service: 0.5% user + 1% kernel
      1.5% 700/audioserver: 0.8% user + 0.7% kernel / faults: 7 minor
      1.4% 1208/com.android.systemui: 1% user + 0.4% kernel / faults: 1544 minor
      1.2% 293/irq/480-synapti: 0% user + 1.2% kernel
      1.2% 676/android.hardware.sensors@1.0-service: 0.5% user + 0.7% kernel
      1.2% 19410/kschedfreq:2: 0% user + 1.2% kernel
      1.1% 2497/kworker/u8:1: 0% user + 1.1% kernel
      1% 4675/com.google.android.apps.nexuslauncher: 0.7% user + 0.2% kernel / faults: 1683 minor
      0.9% 50/smem_native_rpm: 0% user + 0.9% kernel
      0.9% 691/kschedfreq:0: 0% user + 0.9% kernel
      0.8% 4548/kworker/0:2: 0% user + 0.8% kernel
      0.8% 4773/kworker/u8:8: 0% user + 0.8% kernel
      0.7% 5218/kworker/u8:7: 0% user + 0.7% kernel
      0.7% 5097/kworker/0:3: 0% user + 0.7% kernel
      0.7% 357/nanohub: 0% user + 0.7% kernel
      0.5% 5309/com.google.android.gms: 0.4% user + 0.1% kernel / faults: 3806 minor
      0.5% 244/kgsl_worker_thr: 0% user + 0.5% kernel
      0.5% 3089/kworker/u8:3: 0% user + 0.5% kernel
      0.4% 3515/kworker/0:1: 0% user + 0.4% kernel
      0.3% 275/spi6: 0% user + 0.3% kernel
      0.3% 675/android.hardware.power@1.1-service.marlin: 0.1% user + 0.1% kernel
      0.3% 10/rcuc/0: 0% user + 0.3% kernel
      0.2% 1184/VosMCThread: 0% user + 0.2% kernel
      0.2% 17/ksoftirqd/1: 0% user + 0.2% kernel
      0.2% 23/ksoftirqd/2: 0% user + 0.2% kernel
      0.2% 479/logd: 0.1% user + 0% kernel / faults: 11 minor
      0.2% 8412/adbd: 0% user + 0.1% kernel / faults: 1392 minor
      0.2% 680/android.hardware.wifi@1.0-service: 0% user + 0.1% kernel
      0.2% 4059/kworker/1:1: 0% user + 0.2% kernel
      0.1% 1378/com.android.phone: 0.1% user + 0% kernel / faults: 312 minor
      0.1% 5970/com.tencent.mobileqq:MSF: 0.1% user + 0% kernel / faults: 145 minor
      0.1% 690/msm_irqbalance: 0% user + 0.1% kernel
      0.1% 3513/kworker/2:1: 0% user + 0.1% kernel
      0.1% 4623/com.tencent.mtt:service: 0% user + 0% kernel / faults: 283 minor
      0.1% 4414/kworker/1:2: 0% user + 0.1% kernel
      0.1% 356/irq/472-nanohub: 0% user + 0.1% kernel
      0.1% 4826/com.eg.android.AlipayGphone:push: 0% user + 0% kernel / faults: 135 minor
      0.1% 355/irq/478-nanohub: 0% user + 0.1% kernel
      0.1% 162/vsync_retire_wo: 0% user + 0.1% kernel
      0% 1795/perfd: 0% user + 0% kernel / faults: 233 minor
      0% 4779/kworker/2:3: 0% user + 0% kernel
      0% 8376/com.eg.android.AlipayGphone: 0% user + 0% kernel / faults: 6 minor
      0% 1791/irq/19-408000.q: 0% user + 0% kernel
      0% 4245/kworker/3:1: 0% user + 0% kernel
      0% 610/jbd2/sda35-8: 0% user + 0% kernel
      0% 734/rild: 0% user + 0% kernel / faults: 176 minor
      0% 8430/com.tencent.mm: 0% user + 0% kernel / faults: 74 minor
      0% 480/servicemanager: 0% user + 0% kernel
      0% 16/rcuc/1: 0% user + 0% kernel
      0% 638/netd: 0% user + 0% kernel / faults: 276 minor
      0% 716/thermal-engine: 0% user + 0% kernel
      0% 1182/wlan_logging_th: 0% user + 0%

**Comment by hero0812** [comment]
E/ActivityManager: ANR in cn.bingoogolapple.bgabanner.demo (cn.bingoogolapple.bgabanner.demo/.ui.activity.MainActivity)
    PID: 5591
    Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 26.  Wait queue head age: 5563.1ms.)
    Load: 7.41 / 6.72 / 5.87

**Comment by kylinzs** [comment]
遇到同样的问题。

**Comment by lyldding** [comment]
分析了一下可能是切换的position值不对，导致循环耗时出现ANR，详情见https://blog.csdn.net/lylddingHFFW/article/details/89212664
