### ISSUE TITLE
java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by XuEnhao** [bingoogolapple/BGABanner-Android#201]
在OPPO PBEM00 上 会有 java.lang.ArithmeticException: divide by zero 其他手机无异常 
<img width="823" alt="image" src="https://user-images.githubusercontent.com/30336000/48342200-035c2780-e6aa-11e8-8e04-1687cdc96fdd.png">
代码片段 mViews.size();可能等于0 所有报错了

**Comment by alanzyz** [comment]
作者竟然没回复，有点吃惊了。
