### ISSUE TITLE
作为header添加到recyclerview中出现各种问题

### ISSUE THREAD

**Issue by po1arbear** [bingoogolapple/BGABanner-Android#208]
滑动无动画、手指触摸和自动轮播冲突

**Comment by bingoogolapple** [comment]
从不可见到可见时动画是直接切换的（解不了），第二次就好了

手指触摸和自动轮播冲突在 demo 里没复现 https://github.com/bingoogolapple/BGABanner-Android/blob/master/demo/src/main/java/cn/bingoogolapple/bgabanner/demo/ui/activity/RecyclerViewDemoActivity.java 如果有时间可以写个demo传到GitHub贴一下链接
