### ISSUE TITLE
请问可以设置这种圆角吗?设置背景没有效果

### ISSUE THREAD

**Issue by kinghom** [bingoogolapple/BGABanner-Android#209]
![tim 20181218162555](https://user-images.githubusercontent.com/23691629/50141304-1f269f00-02e2-11e9-92c4-06efc1a2e99f.png)

**Comment by kinghom** [comment]
![tim 20181218162555](https://user-images.githubusercontent.com/23691629/50141393-585f0f00-02e2-11e9-8b6f-76b76508f8f2.png)

**Comment by bingoogolapple** [comment]
你可以自定义 banner 的 item layout，在 setData 的第一个参数传进去
参考 demo 中的：https://github.com/bingoogolapple/BGABanner-Android/blob/master/demo/src/main/java/cn/bingoogolapple/bgabanner/demo/ui/activity/FrescoDemoActivity.java

**Comment by Yexi** [comment]
改成了圆角的布局但是滑动的时候会变成平角

**Comment by Yexi** [comment]
> 你可以自定义 banner 的 item layout，在 setData 的第一个参数传进去
> 参考 demo 中的：https://github.com/bingoogolapple/BGABanner-Android/blob/master/demo/src/main/java/cn/bingoogolapple/bgabanner/demo/ui/activity/FrescoDemoActivity.java

改成了圆角的布局但是滑动的时候会变成平角
