### ISSUE TITLE
控件开启无限轮播后 ，快速滑动，ANR现象分析

### ISSUE THREAD

**Issue by lyldding** [bingoogolapple/BGABanner-Android#213]
分析了一下可能是切换的position值不对，导致循环耗时出现ANR，详情见https://blog.csdn.net/lylddingHFFW/article/details/89212664

**Comment by bingoogolapple** [comment]
非常感谢

早上试了下，即使区分了左滑和右滑，还是存在 ANR。最近有比较紧急的事情要处理，下周空了再看下

**Comment by bingoogolapple** [comment]
确实是这里的问题，之前改了没依赖最新版
