### ISSUE TITLE
当Banner里的view大于两个才会自动轮播，介绍里说的是大于1个就会自动轮播。

### ISSUE THREAD

**Issue by WarriorYu** [bingoogolapple/BGABanner-Android#217]
从源码看是当小于3条数据就不自动轮播了，为什么介绍里说的是大于1条就自动轮播呢？这里设置为3条是基于什么考虑呢？
 public void setData(List<View> views, List<? extends Object> models, List<String> tips) {
        ...

        if (mAutoPlayAble && views.size() < 3 && mHackyViews == null) {
            mAutoPlayAble = false;
        }

**Comment by tt905** [comment]
同问

**Comment by zhangshaobo87** [comment]
可以自己设置的呀，demo里边有

**Comment by bingoogolapple** [comment]
![image](https://user-images.githubusercontent.com/8949716/68064177-4ac44380-fd53-11e9-8d6c-03c5a25fe057.png)
如果不管多少页都要开启自动轮播的话则直接 BGABanner.setAutoPlayAble(true);

**Comment by lythonliu** [comment]
在使用public void setData(List<View> views, List<? extends Object> models, List<String> tips) {...}这个方法，并且不使用网络图时确实有问题，调试了半天没有匹配出合适的设置，存在手动滑动时第一页无法往前翻页，以及向左滑出现空白内容问题，索性重写一下这个方法
