### ISSUE TITLE
不支持kotlin？？

### ISSUE THREAD

**Issue by czl0325** [bingoogolapple/BGABanner-Android#223]
![image](https://user-images.githubusercontent.com/2100549/60343350-5f2fb280-99e6-11e9-92d4-9e11b570939c.png)

请问在viewholder里面怎么写？这样报错。

**Comment by Joslyn-Chen** [comment]
`subject_banner.setAdapter(object : Adapter<ImageView, String> {
      override fun fillBannerItem(banner: BGABanner, itemView: ImageView, model: String?,
        position: Int) {
        itemView.loadUrl(this@SubjectActivity, model)
      }
    })`
