### ISSUE TITLE
在onPageChange中使用stopAutoPlay无效

### ISSUE THREAD

**Issue by W2009-Cai** [bingoogolapple/BGABanner-Android#233]
在onPageChange中使用stopAutoPlay无效.浩哥可以解答一下吗  @bingoogolapple

**Comment by qq574699613** [comment]
@Override
                    public void onPageSelected(int index) {
                        if (mList.get(index) ==3) {
                            banner.stopAutoPlay();
                        } else {
                             banner.startAutoPlay();
                        }
                    }
代码是这样
