### ISSUE TITLE
停用了自动轮播，就不能无限循环了

### ISSUE THREAD

**Issue by RmondJone** [bingoogolapple/BGABanner-Android#248]
停用了自动轮播，就不能无限循环了

**Comment by litchicoder** [comment]
我也是被这个搞了

**Comment by RmondJone** [comment]
> 我也是被这个搞了
> ![image](https://user-images.githubusercontent.com/20694411/86885306-9c656f00-c127-11ea-92dc-b5e93d38f67d.png)
> 
> * [ ]

https://github.com/wenchaosong/Banner,我用另一个库了，虽然星不多，但是感觉比这个稳
