### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by zhaoxiuyu** [bingoogolapple/BGABanner-Android#36]
内存回收不掉，你知道吗

**Comment by bingoogolapple** [comment]
@zhaoxiuyu 能否帮忙改了后提个pr贡献点代码

**Comment by bingoogolapple** [comment]
你是指PagerAdapter的destroyItem方法里没有销毁item吗？
```Java
@Override
public void destroyItem(ViewGroup container, int position, Object object) {
}
```

**Comment by zhaoxiuyu** [comment]
加载图片后内存上涨10M，退出页面后内存并没有回落，或者说有什么方法可以进行回收.

**Comment by genius158** [comment]
其实个人在做ImageView的时候，经常也会出现内存控制问题，建议改用Fresco来实现图片的显示，fresco自带内存处理非常方便 @bingoogolapple

**Comment by SomnusWu** [comment]
Banner  滑动  . 内存无限递增 , 有办法控制么  .

**Comment by gaobingbing** [comment]
@bingoogolapple 内存递增的原因是，View持有了对象的引用，导致内存无法回收。
`BGABanner mBanner = (BGABanner) findViewById(R.id.banner);
mBanner.setOnPageChangeListener(new ViewPager.SimpleOnPageChangeListener(){

        @Override
        public void onPageSelected(int position){
		    int lastPosition = -1;
            View lastItemView = null;            
            if (position == 0 && mBanner.getItemCount() > 1) {
                //当前是第一个,获取最后一个
                lastPosition = mBanner.getItemCount() - 1;
            } else if (position > 0) {
                lastPosition = position - 1;
            }
			if(lastPosition!=-1){
				lastItemView = mBanner.getItemView(lastPosition);
			}
			//以下内容可暴露出来给用户手动重置View所引用对象
            if (lastItemView != null) {
                ImageView mImageView = (ImageView) lastItemView.findViewById(R.id.imageview);
                mImageView.setImageDrawable(null);
		//...其他更多
            }
        }
    });`

**Comment by bingoogolapple** [comment]
#151
