### ISSUE TITLE
README 的插图可以优化一下

### ISSUE THREAD

**Issue by D-clock** [bingoogolapple/BGABanner-Android#45]
如题，GIF图看不清而且掉帧有些严重，可以考虑 Genymotion虚拟机+GifCam 重新录制一下Gif效果图！

**Comment by bingoogolapple** [comment]
之前是想减少开发者 clone 代码到本地的时间，没有把图片放到仓库里，是先把图片传到七牛云存储的，结果最近github显示七牛云存储里的图片会卡顿。

现在改成了 [单独建个issues来保存截屏以便获取图片路径](https://github.com/bingoogolapple/BGABanner-Android/issues/46) ，这样既省去了开发者 clone 代码时将截图载到本地，又不会卡顿了:smile:
