### ISSUE TITLE
为何我集成到我的项目里,轮播会有问题，我完全按照你的DEMO来用BGABanner的啊？

### ISSUE THREAD

**Issue by yaochangliang159** [bingoogolapple/BGABanner-Android#48]
我添加了三张轮播图的url，开始轮播，但是每次刚到第二张，还没有等待一点间隔时间，立马就切换到第三张了，不知道怎么回事，你的DEMO好好的啊，我只是在我的项目里作为listview的headView了啊
调用代码如下：
`    BGABanner vp_view ;
 vp_view = (BGABanner) headView.findViewById(R.id.vp);

vp_view.setAdapter(this);
        List<String> ads=new ArrayList<>();
        List<String> tips=new ArrayList<>();
        tips.add("");
        tips.add("");
        tips.add("");
        ads.add("http://www.pc6.com/up/2014-9/14113709517423674.jpg");
        ads.add("http://pic0.mofang.com/2014/0922/20140922094300855.jpg");
        ads.add("http://pic0.mofang.com/2014/1113/20141113110312116.jpg");
        vp_view.setData(ads,tips);

  @Override public void fillBannerItem(BGABanner banner, View view, Object model, int position) {
        Picasso.with(getActivity())
            .load((String)model)
            .placeholder(R.drawable.placeholder_ad)
            .into((ImageView) view);
    }

`
xml如下:
` <cn.bingoogolapple.bgabanner.BGABanner
            android:id="@+id/vp"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_alignParentLeft="true"
            app:banner_indicatorGravity="center_horizontal"
            app:banner_pointDrawable="@drawable/bga_banner_selector_point_solid"
            app:banner_transitionEffect="stack" />`
作者求解啊，，真心觉得你这库很好，，为什么到我这里就出问题了呢，，，我昨天还给你打赏了，，帮帮我吧。。。

**Comment by yaochangliang159** [comment]
xml如下：
`
  <cn.bingoogolapple.bgabanner.BGABanner
            android:id="@+id/vp"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_alignParentLeft="true"
            app:banner_indicatorGravity="center_horizontal"
            app:banner_pointDrawable="@drawable/bga_banner_selector_point_solid"
            app:banner_transitionEffect="stack" />
`

**Comment by bingoogolapple** [comment]
@yaochangliang159 不好意思，stack这种切换效果目前还有问题，麻烦先换成其他切换效果，后期再优化stack

**Comment by yaochangliang159** [comment]
OKOK,换成别的就解决了~~~你可以close这个issue了

**Comment by bingoogolapple** [comment]
先不关吧，等后面空了看能不能修复
