### ISSUE TITLE
目前不支持当前图片放大缩小的功能

### ISSUE THREAD

**Issue by ming1zhou88** [bingoogolapple/BGABanner-Android#50]
你好，
       我想问一下我可以用BGABanner实现每个轮播的图片放大缩小么？因为现在的开发需求要展示站内详情示意图，但是没有放大缩小的功能。

**Comment by bingoogolapple** [comment]
大图预览不是Banner这个库要做的事情哈，大图预览参考下 [BGAPhotoPicker-Android](https://github.com/bingoogolapple/BGAPhotoPicker-Android)

**Comment by bailyzheng** [comment]
@bingoogolapple BGABanner在可以缩放显示完整的图吗？附件1是原图，附件2是显示的图，只显示原图中间的部分
![2](https://cloud.githubusercontent.com/assets/3355710/18614416/eff5295c-7dc0-11e6-8d33-2163554f35df.PNG)
![1](https://cloud.githubusercontent.com/assets/3355710/18614417/f1cccf5a-7dc0-11e6-84c4-a6d0b7fb9e3b.PNG)

**Comment by bailyzheng** [comment]
@bingoogolapple BGABanner能缩放显示完整的图吗？附件中图1是原图，图2是显示的图，只显示了原图中间一部分
![1](https://cloud.githubusercontent.com/assets/3355710/18614446/8b1ba258-7dc1-11e6-978a-ffb3c37b4e3c.PNG)
![2](https://cloud.githubusercontent.com/assets/3355710/18614454/aa3cfbdc-7dc1-11e6-9e56-1f595bd61106.PNG)

**Comment by SamuelY** [comment]
你看一下源碼就知道 
當你在setAdapter時要new一個BGABanner.Adapter
這裡面就要你實作fillBannerItem()
demo中是利用 Glide這個library來show image
只要在裡面多加一個.fitCenter()就OK了

        Glide.with(mFragment)
                .load(model)
                .fitCenter()
                .placeholder(R.drawable.test_event)
                .error(R.drawable.test_event)
                .into((ImageView) view);

**Comment by bingoogolapple** [comment]
mContentBanner.setAdapter(new BGABanner.Adapter<ImageView, String>() {
    @Override
    public void fillBannerItem(BGABanner banner, ImageView itemView, String model, int position) {
        Glide.with(MainActivity.this)
                .load(model)
                .placeholder(R.drawable.holder)
                .error(R.drawable.holder)
                .centerCrop()
                .dontAnimate()
                .into(itemView);
    }
});

mContentBanner.setData(Arrays.asList("网络图片路径1", "网络图片路径2", "网络图片路径3"), Arrays.asList("提示文字1", "提示文字2", "提示文字3"));
