### ISSUE TITLE
onBannerItemClick 的model和position总是同一个

### ISSUE THREAD

**Issue by qq8057656qq** [bingoogolapple/BGABanner-Android#52]
我设置数据源的方式如下：
        banner.setAdapter(new HomeBannerAdapter(mContext));
        banner.setOnItemClickListener(onItemClickListener);
        banner.setData(R.layout.home_banner_layout,resultInfoEntities,null);
在onBannerItemClick 中，model和position总是不对，
我通过int index =  banner.getCurrentItem();获取当前真正的位置，是我的
写法有问题造成的吗？

**Comment by bingoogolapple** [comment]
用最新的 v2.1.2 版本试试
