### ISSUE TITLE
banner用在Viewpager多个Fragment中 切换Fragment后 首次播放失去动画

### ISSUE THREAD

**Issue by envyfan** [bingoogolapple/BGABanner-Android#53]
我的业务场景 ：
在ViewPager中每个Fragment都有一个自动播放的Banner， 当当前Fragment用户不可见时（ setUserVisibleHint ）我就stopBanner播放，当Fragment用户可见时我就startBanner播放。

Banner能正常如我所愿地播放与暂停，但是如果从当前页切换到别的页的时候，首次播放Banner时会没有动画直接 跳过Banner第一张图片。当Banner第二张图片开始轮播时，轮播又恢复正常有切换动画。看了很旧源码不知道哪里出问题了。

**Comment by envyfan** [comment]
相邻的两个Fragmnet切换不存在该问题，当切到不相邻的就会有，猜测应该与 Fragment被回收什么的 相关联

**Comment by envyfan** [comment]
拿到Banner的Adapter然后 刷新下Adapter的数据就 不会有这问题了。原理我不懂= - 搞了好久。如果有类似问题的朋友可以参考下

**Comment by bingoogolapple** [comment]
参考最新版 v2.1.3 的 demo https://github.com/bingoogolapple/BGABanner-Android/blob/master/demo/src/main/java/cn/bingoogolapple/bgabanner/demo/ui/activity/RecyclerViewDemoActivity.java

**Comment by DonnyHe** [comment]
@envyfan 你好，我也遇到这个问题了，在viewpager的fragment里面用了轮播，切换到第三个fragment，再切换回来后，banner就没了。你说的解决办法我没怎么看懂，能否再细一点。急，在线等^^

**Comment by envyfan** [comment]
@DonnyHe 我的问题好像和你不一样啊,我的只是失去动画 轮播下一张时才恢复正常, 貌似后来作者修改好了这个bug(我没去尝试) 如果是我那种情况那么 你拿到Banner的实例 取出adapter 刷新一下就不会有这个问题了
