### ISSUE TITLE
BGABanner使用默认图会OOM

### ISSUE THREAD

**Issue by NFLeo** [bingoogolapple/BGABanner-Android#54]

**Comment by bingoogolapple** [comment]
你是在引导页使用，还是做自动轮播？

**Comment by NFLeo** [comment]
引导页额

**Comment by bingoogolapple** [comment]
你图片放在哪个目录的

**Comment by NFLeo** [comment]
就是你demo里面的，我就把你的demo挪下来修改的

**Comment by bingoogolapple** [comment]
三个问题：
1.用的我 demo 里的图片还是自己的图片？
2.如果不是用的我 demo 里的图片，你图片尺寸是多少？
3.把我的demo挪下来修改时，图片放在哪个目录里的？

**Comment by NFLeo** [comment]
是你的图片，xx文件夹里面的

**Comment by bingoogolapple** [comment]
我 demo 里的图片放 xhdpi 里都不会蹦，你拿去放 xxhdpi 里更不会蹦才对呀，除非你放到了 hdpi 里

**Comment by NFLeo** [comment]
后来我改好了，忘记改了哪里了， 貌似是你图片展示的时候没做处理，我换了个Glide就好了

**Comment by bingoogolapple** [comment]
!!! 应该就是把图片目录放错了

**Comment by NFLeo** [comment]
是吗？我应该没挪位置吧，好久了额，忘了额，不过写的挺好用的，赞赞赞
