### ISSUE TITLE
可以支持fresco加载吗?

### ISSUE THREAD

**Issue by peng8350** [bingoogolapple/BGABanner-Android#55]
我想通过fresco来加载图片,但是加载的话必须使用SImpledraweeview而不是imageview,那个Adapter貌似也只能是ImageView的,有没有办法就是自定义一个item.xml,这样显示图片?

**Comment by bingoogolapple** [comment]
可以的，你看一下setData的重载方法

![image](https://cloud.githubusercontent.com/assets/8949716/19294349/44b1c180-905e-11e6-8b00-c6336a6de3bb.png)

然后在adapter的方法fillBannerItem(BGABanner banner, View view, Object model, int position)里的view就是你穿进去的布局资源的跟布局

**Comment by jingtonglong** [comment]
你再说说你的需求呢？说的很模糊啊，具体一点点呢

**Comment by peng8350** [comment]
@bingoogolapple Thanks!
