### ISSUE TITLE
每次切换,都会调用fillbanneritem重新加载图片

### ISSUE THREAD

**Issue by peng8350** [bingoogolapple/BGABanner-Android#56]
我想实现这个需求,就是切换图片不把view回收,防止每次切换图片重新加载会卡顿,用户体验不好。我看了以下你的代码,确实重写了ondestroyitem这个方法,并让他不调用父类回收view,确实这样写可以防止回收view,但是就搞不懂为什么fillbanneritem这方法还会调用。

**Comment by peng8350** [comment]
刚经过调试,并不是加载图片引起UI卡顿。
![2016-10-13 13-10-36](https://cloud.githubusercontent.com/assets/19425362/19339148/30ce2e50-9154-11e6-98d1-de53dbdfab75.png)
如图,最外围是ScrollView,ScrollView里面嵌套banner,gridview,3个Asymmgridview(表格布局开源)。
问题根本:每当滑动banner时,其他的gridview或者listview都会多次调用onmeasure这个方法重新测量布局。

**Comment by peng8350** [comment]
问题已经解决,与banner无关,我把viewpager gridview外围的RelativeLayout

**Comment by CeciliaKasumi** [comment]
你好这个问题请问解决了吗我也遇到了类似的问题
