### ISSUE TITLE
为什么我总会出现刷新后很多空白,有的滑动下出现图片,有的滑动也不能出现图片

### ISSUE THREAD

**Issue by RainliFu** [bingoogolapple/BGABanner-Android#59]
我是将这个作为下拉刷新控件的头部的,总会出现刷新后banner空白,但是滑动下有些能出现,有些不能出现

**Comment by bingoogolapple** [comment]
没明白你的意思，详细描述或者截图看一下

**Comment by greatflag** [comment]
我也碰到这样的问题，我的APP是viewpager+BottomNavigationBar，当开启自动轮播时，APP滑到第三四页，再回到首页，自动轮播下一张就会空白。下拉刷新后，整个页面空白了，关闭轮播就没事。首页的adapter也是用你的库。

**Comment by wonxll** [comment]
@RainliFu @greatflag 兄弟，你们是怎么处理的啊。。。

**Comment by RainliFu** [comment]
@wonxll 我后来自己写的，没有用这个库
