### ISSUE TITLE
手指在vp上移动一下，松开会跳转上一页或者下一页

### ISSUE THREAD

**Issue by IceHermes** [bingoogolapple/BGABanner-Android#6]
手指在vp上移动一下，松开会跳转上一页或者下一页，

**Comment by IceHermes** [comment]
从page2开始 稍微拖动一下 按住几秒钟  松开回到上一个page （有bug）

**Comment by Lee-swifter** [comment]
这个问题我也发现了，在点击时，也会出现这个现象。。#8

**Comment by HanXiaoMa** [comment]
当连续用手指滑动几页的时候,然后点击 就会自动跳到下一页

**Comment by Lee-swifter** [comment]
这个问题估计一时半会不好解决，我已经更换到另一个项目了。如果你们急于解决这个问题，不妨试一试这个项目：https://github.com/H07000223/FlycoBanner_Master
