### ISSUE TITLE
按照demo写的启动页滑动卡顿是什么原因呢？

### ISSUE THREAD

**Issue by love-311** [bingoogolapple/BGABanner-Android#63]

**Comment by bingoogolapple** [comment]
你用这个库是做引导页功能，还是做无线轮播功能

**Comment by love-311** [comment]
你好，这个问题我处理掉了，是我自己没有指定图片详细的目录导致的，这里我想给你提一个问题就是你们的九宫格图片查看大图在图片比较大的情况下滑动非常的卡顿，希望可以改善。。

**Comment by bingoogolapple** [comment]
https://github.com/bingoogolapple/BGAPhotoPicker-Android 这个库？

**Comment by is1988** [comment]
@love-311 请问引导页卡顿的问题 你是怎么解决的 还请指点

**Comment by bingoogolapple** [comment]
@is1988 注意图片放的资源目录 xhdpi、xxhdpi 要和设计稿对应
