### ISSUE TITLE
banner频繁左右滑动app卡死继而ANR，不知道什么原因，望解答，群加不进去了

### ISSUE THREAD

**Issue by liuhua343527** [bingoogolapple/BGABanner-Android#64]
使用起来确实很方便，各项功能都很好，感谢！
但是这个无意测出来的bug希望作者可以关注一下，完善的越来越好

**Comment by shejishi** [comment]
同样遇到这种问题，求解

**Comment by bingoogolapple** [comment]
用最新的 2.1.2 版本试试，如果还有这个问题，麻烦提供一下出问题的 demo

**Comment by bingoogolapple** [comment]
你用这个库是做引导页功能，还是做无线轮播功能

**Comment by liuhua343527** [comment]
是用于无限轮播功能

**Comment by liuhua343527** [comment]
是用于无限轮播功能

**Comment by kk-sugar** [comment]
我也遇到过这个问题，不知道你们解决了没有，轮播的时候左右左右滑动，大概10 到30次左右就会出现anr

**Comment by lyldding** [comment]
分析了一下可能是切换的position值不对，导致循环耗时出现ANR，详情见https://blog.csdn.net/lylddingHFFW/article/details/89212664
