### ISSUE TITLE
为什么不会自动轮播，要点一下才会开始呢？是RecyclerView添加头布局的问题吗？

### ISSUE THREAD

**Issue by fandazeng** [bingoogolapple/BGABanner-Android#71]

**Comment by bingoogolapple** [comment]
用的哪个版本？

**Comment by bingoogolapple** [comment]
参考最新版 v2.1.3 的 demo， https://github.com/bingoogolapple/BGABanner-Android/blob/master/demo/src/main/java/cn/bingoogolapple/bgabanner/demo/ui/activity/RecyclerViewDemoActivity.java

**Comment by fandazeng** [comment]
找到问题了，跑的是我自己的demo，我用的RecyclerView，添加头布局的处理的问题，谢谢！

**Comment by bingoogolapple** [comment]
用最新的 v2.1.3 版本吧，修复了 RecyclerView 里用的一些问题
