### ISSUE TITLE
能不能添加一个属性，设置滚动区域圆角呢

### ISSUE THREAD

**Issue by zzzzzzzzzy** [bingoogolapple/BGABanner-Android#76]

**Comment by bingoogolapple** [comment]
滚动区域是指整个 BGABanner 区域？如果是的话你可以在 BGABanner 外面包裹一层 CardView 来实现圆角

**Comment by zzzzzzzzzy** [comment]
不好意思，可能是我表达错误。。我这里用的效果是把分页的图片小圆点放在了滚动区域的下面独立显示，滚动区域只有图片了，想把只显示图片的区域做成圆角的，小圆点在图片外保持不变。如果包裹一层 CardView就只能上半部分圆角了。

**Comment by bingoogolapple** [comment]
![image](https://cloud.githubusercontent.com/assets/8949716/21934516/a34f79b0-d9e4-11e6-99bb-960085841f2a.png)

这种？
