### ISSUE TITLE
Could not find bga-banner.aar

### ISSUE THREAD

**Issue by TwoSX** [bingoogolapple/BGABanner-Android#85]
Error:Could not find bga-banner.aar (cn.bingoogolapple:bga-banner:2.1.7).
Searched in the following locations:
    https://jcenter.bintray.com/cn/bingoogolapple/bga-banner/2.1.7/bga-banner-2.1.7.aar

**Comment by bingoogolapple** [comment]
用最新版 2.2.0

如果还不行，就升级 AS 和 Gradle 插件
