### ISSUE TITLE
源码问题

### ISSUE THREAD

**Issue by codepython** [bingoogolapple/BGABanner-Android#9]
在demo里面的App.java，下面代码是什么作用？需要其他依赖库吗？

@Override
    public void onCreate() {
        super.onCreate();

        sInstance = this;
        mEngine = new Retrofit.Builder()
                .baseUrl("https://raw.githubusercontent.com/bingoogolapple/BGABanner-Android/server/api/")
                .addConverterFactory(GsonConverterFactory.create())
                .build().create(Engine.class);

        Fresco.initialize(this);
    }

**Comment by bingoogolapple** [comment]
@codepython 这是配置Retrofit这个网络网络请求库的代码，与轮播图库没关系
